### ISSUE TITLE
Can this scrape be done on mac ? 

### ISSUE THREAD

**Issue by hornivorouss** [sim0n00ps/OF-DL#187]
Can this code be done on Mac I cannot download c++ on max the fourth step which is mentioned

**Comment by sim0n00ps** [comment]
I don't have a Mac running MacOS to test with, I have one but it has windows 10 on it so as far as I'm aware no it's not possible to use this on a mac

**Comment by hornivorouss** [comment]
Ok thanks any other scrape which can be done in mac ?

**Comment by jk779** [comment]
You can virtualize Windows, for example with a paid program (e.g. Parallels) or with a free Tool. I recommend the free `UTM`: https://mac.getutm.app/ 

A) If you're on a Apple Silicon chip, you have to download an ARM-Version of Windows:

1. go to https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewarm64 and log into you ms account.
2. if it says you have to join in the insider program, register for it (its free)
3. go back to the download page and select `Windows 11 Client Arm64 Beta Channel` and download that.
4. Create a Windows VM in UTM (select "Virtualize" instead of "Emulate" (=the one with the rabbit))

I'm pretty sure they disable the TPM-Checking etc. in the insider versions.

----

B) If you're on an Intel Mac, then you can download preferably a Windows 10, e.g. https://www.microsoft.com/en-us/software-download/windows10ISO. Afaik you can skip activation and Serial entry for a couple of weeks, if you don't have a Windows 10 key. Buy they can be bought online for < $5.
(Don't try to virtualize Windows **_11 for x64_**, because it checks for the presence of a TPM device, which is nasty.)

Then create a new VM in UTM and select Virtualize as well. 

Hope this helps :)

**Comment by Dreamkiller711** [comment]
> Can this code be done on Mac I cannot download c++ on max the fourth step which is mentioned

Works successfully on my M1 iMac and I don't know much about coding! Just asked Bing's AI and it helped me setup the requirements:

— Download the latest .NET SDK v8 from Microsoft
— Version 7.0 was required so I also got .NET runtime 7.0
— Download source code from GitHub
— Open Terminal and type `cd <path/to/source/code/folder`
— Type `dotnet build`
— Should be able to run with `dotnet run` if no errors

Place auth.json and config.json in /OF-DL-OFDLV1.7.48/OF DL folder, set them up and enjoy!

**Comment by melithine** [comment]
As a follow-up, the supported method these days is to use the Docker image for non-Windows OSes.
