### ISSUE TITLE
The window closes by itself right after successful authentication

### ISSUE THREAD

**Issue by KingVitto** [sim0n00ps/OF-DL#24]
Greetings!
The thing doesn't work for me :(

I launch the OF DL.exe, get green confirmations that 3 exe's located successfully, in a second I get green "logged in successfully as *my username & id*" and then the window just closes.

I'm on Win7 64

Any thoughts?

**Comment by KingVitto** [comment]
![Capture](https://github.com/sim0n00ps/OF-DL/assets/135433495/d5f9ba5b-1e42-4407-bc6a-ee7b67a94d15)
I ran the exe through cmd and that's what I got...

**Comment by sim0n00ps** [comment]
I can look into it but I don't know if it would affect the script aesthetically by removing the use of ANSI.

**Comment by sim0n00ps** [comment]
Yeah I can't really support older OS versions like Windows 7/8.1 because if I remove the use of ANSI its going to essentially make the program unusable as it depends on it in a lot of areas so it will be a massive task to try and get the program to function the same as it does now without ANSI. My recommendation would to update to Windows 10 or 11 as Windows 7 and 8.1 are no longer supported as of 10th January 2023.
