### ISSUE TITLE
auth failed

### ISSUE THREAD

**Issue by segiru** [sim0n00ps/OF-DL#260]
It was working normally for me a few weeks ago, now I download the update, enter the data and it no longer works, the following appears to me
![image](https://github.com/sim0n00ps/OF-DL/assets/106352079/889ea120-68c9-462f-8cc0-1ca60f6b2bab)

**Comment by segiru** [comment]
I don't know what happened but I solved it, downloaded the files again, put the data back in and now it works

**Comment by greyhat94** [comment]
Hello, I had the same issue. I've fixed by entering the "User ID" value correctly.

**Comment by lucacham** [comment]
I ran into the same problem today. I compared the latest cookie and found that the value has changed. After repairing it, it can be used normally.

**Comment by sealsnipe** [comment]
I'm having the same problem, not solved yet.

I ran into this with a working downloader. It worked in January and when I opened it today it gave mit thia error.

So I went ahead and checked the network console for new values. turns out everything changed. I put the values in and tried again. Still Auth failed. So I check the values again:
the sess token changed.

It turns out every time I try a new sess token I start the downloader, it says auth failed, I get kicked from OF in the browser to the OF login screen in browser and when I log back in the sess token changed.  Same is happening when I close the browser after retrieving the sess token and before starting the downloader.

Am I missing something?

**Comment by sim0n00ps** [comment]
> I'm having the same problem, not solved yet.
> 
> I ran into this with a working downloader. It worked in January and when I opened it today it gave mit this error.
> 
> So I went ahead and checked the network console for new values. turns out everything changed. I put the values in and tried again. Still Auth failed. So I check the values again:
> the sess token changed.
> 
> It turns out every time I try a new sess token I start the downloader, it says auth failed, I get kicked from OF in the browser to the OF login screen and when I log back in to OF the sess token changed.  Same is happening when I close the browser after retrieving the sess token and before starting the downloader.
> 
> Am I missing something?

Re-copy your user-agent as well, that changes after every browser update

**Comment by sealsnipe** [comment]
noice. that was it. cheers!

**Comment by melithine** [comment]
> Re-copy your user-agent as well, that changes after every browser update

This seems to be a very common issue that keeps getting raised here. Maybe it would be a good idea to explicitly mention that in the error. That way, more people might realize they need to check that instead of coming here, operating an issue, and waiting for someone to reply to it with the same advice constantly. Feels like it's a waste of your time right now, imo.

**Comment by deadbeatdandylyon** [comment]
Hello, I am currently running into a similar issue 

![image](https://github.com/sim0n00ps/OF-DL/assets/59564520/0ae27fd6-4b8f-4bf9-9818-b6f9c1f75488)

I noticed that the Auth file has changed in the information that is required 

I have put all the required information in but I keep getting the same error message. is there a sample of what the new auth file should look like?
