### ISSUE TITLE
unable to download the content

### ISSUE THREAD

**Issue by kililua** [sim0n00ps/OF-DL#261]
shows this error, how is the solution? help please

![Screenshot 2024-01-17 033035](https://github.com/sim0n00ps/OF-DL/assets/106385047/f53a5a45-bfcf-4e24-b9ff-0ddbc99b8b1a)

**Comment by kililua** [comment]
![Screenshot 2024-01-17 034603](https://github.com/sim0n00ps/OF-DL/assets/106385047/851f738a-fbf9-47c2-aaf8-982b755c7b2c)

**Comment by greyhat94** [comment]
Hi, what kind of version are you using? Is it the first time that you're experiencing this issue? Was everything good with the configuration?

**Comment by canyud** [comment]
> Hi, what kind of version are you using? Is it the first time that you're experiencing this issue? Was everything good with the configuration?

Hi, its the latest one, and yeah my first time experiencing this error.

**Comment by greyhat94** [comment]
Was everything good with the configuration of the file? Once you run the executable file, is the software able to find the path of "ffmpeg.exe", "auth.json", and "config.json"?

**Comment by canyud** [comment]
> Was everything good with the configuration of the file? Once you run the programme, is the software able to find the path of "ffmpeg.exe", "auth.json", and "config.json"?

Yes, I can log into the program, all auth was good, i just cant download the content of the creator ( the DRM i guess? )

**Comment by greyhat94** [comment]
Can you try downloading a single post instead of all the content? I am not
an expert on the subject, but I believe that your error may depend on the
temporary inactivity of the CDM service. In any case, let me know if you
can download a single piece of content. A little while ago, I conducted a
test on a single video, almost certainly protected by DRM, and the
operation was successful. However, I don't know why, but OnlyFans banned
another profile for me, which had never been used either to download
content or to subscribe to the profiles of the various creators.

Il mer 17 gen 2024, 20:16 canyud ***@***.***> ha scritto:

**Comment by fidelio959** [comment]
I can tell you that I also tried download a single DRM video with the same error. How can I check if it a problem with CDM service? I am using the same configuration as 10 days ago when I was able to download everything.

**Comment by fidelio959** [comment]
At the end I was able to solve the problem. I used the following command to enable proxy in cmd: set HTTP_PROXY=http://userid:password@address:port. It worked till few weeks ago but I don't why it didn't work yesterday. I don't know if there is another way to enable proxy in cmd.

**Comment by melithine** [comment]
Setting a proxy like that is something you would have to do each terminal session, I believe.

**Comment by fidelio959** [comment]
Indeed is what I do each terminal session and it worked fine till yesterday. Using OF-DL with proxy gave me the above error. I did the same thing without proxy and everything worked fine. I don't like to use the tool with my IP but yesterday I did any attempt to make it work. The problem is related to the DRM videos. I don't know if there are some  netowrk calls that ffmpeg or CDM does to work properly.

**Comment by greyhat94** [comment]
How should I configure the "auth.json" file in order to hide my IP during
the scraping procedure performed through the tool? Were you able to resolve
the error about the content not downloading? I'm waiting for your answer.

Il gio 18 gen 2024, 11:14 fidelio959 ***@***.***> ha scritto:

**Comment by fidelio959** [comment]
I use the following command set HTTP_PROXY=http://userid:password@address:port and for some reason it was wroking well again. I don't know why and how but it did.
