### ISSUE TITLE
Opens then closes immediately 

### ISSUE THREAD

**Issue by robertssteve** [sim0n00ps/OF-DL#269]
As soon as I open OF-DL.exe, it opens and I can see that it says "auth.json located successfully" and then it closes immediately

**Comment by FlavinDoPn3u** [comment]
Check if the FFMPEG_PATH on auth.json is between a single set of quotation marks.
Wrong --> "FFMPEG_PATH": ""C:/Users/User/Downloads/.../ffmpeg.exe""
Right --> "FFMPEG_PATH": "C:/Users/User/Downloads/.../ffmpeg.exe"

**Comment by melithine** [comment]
Beyond that suggestion, open a PowerShell window and then run the program from that window (just change directories to where the program is located and type in `OF-DL.exe`). It should then show the output there rather than opening a new window that closes immediately when the program exits, so you can see the whole output.
