### ISSUE TITLE
help me ! id blob or private key missing problem

### ISSUE THREAD

**Issue by orca7448** [sim0n00ps/OF-DL#281]
![스크린샷 2024-02-16 202743](https://github.com/sim0n00ps/OF-DL/assets/109455325/45de188f-948f-4575-9818-404e1833971c)

how can i  fix this? help me please

**Comment by whimsical-c4lic0** [comment]
You can ignore the warning in yellow. Your problem is that you haven't saved your OF account details to the `auth.json` file. Follow the tutorial video [here](https://github.com/sim0n00ps/OF-DL?tab=readme-ov-file#video-tutorial) or the text instructions [here](https://of-dl.gitbook.io/of-dl/auth). If you've already done this, your web browser may have auto-updated and you'll need to do this again.

**Comment by orca7448** [comment]
oh, my browser had auto updated! thank you for your comment!
