### ISSUE TITLE
Can’t launch ‘OF DL.EXE’ (Ubuntu Linux)

### ISSUE THREAD

**Issue by kevingscript** [sim0n00ps/OF-DL#334]
I’ve been trying to figure this out for days. Can’t get ‘OF DL.exe’ program to launch. Using Ubuntu Linux with the ‘Wine’ command line app (for exe). Any tips greatly appreciated lol.
![IMG_0573](https://github.com/sim0n00ps/OF-DL/assets/56876965/81f3af7b-9e0e-4729-8333-27bf0b7efe29)

**Comment by melithine** [comment]
If you're on Linux, don't use Wine, use the Docker image instead.

**Comment by kevingscript** [comment]
> If you're on Linux, don't use Wine, use the Docker image instead. 

So I setup everything using Docker and have the welcome message. But I'm not greeted with the 'selection prompt'. 
![image](https://github.com/sim0n00ps/OF-DL/assets/56876965/14460fe6-180e-4e23-b9dc-691ff0e97137)

**Comment by melithine** [comment]
I think there are problems with the CDRM project (a third party that generates client decryption keys for Wildvine DRM) at the moment, which is a semifrequent occurrence. If you generate your own keys using Android Studio, you might have better luck. CDRM is meant as a fallback solution if you don't have your own keys, but it's best not to rely on it... it's been offline before due to the maintainer having billing issues, for example.

**Comment by kevingscript** [comment]
> I think there are problems with the CDRM project (a third party that generates client decryption keys for Wildvine DRM) at the moment, which is a semifrequent occurrence. If you generate your own keys using Android Studio, you might have better luck. CDRM is meant as a fallback solution if you don't have your own keys, but it's best not to rely on it... it's been offline before due to the maintainer having billing issues, for example. 

Thanks!!
