### ISSUE TITLE
"cant find file path for FFmpeg"

### ISSUE THREAD

**Issue by Cagecellag** [sim0n00ps/OF-DL#335]
So idk what i did wrong, i followed the tutorial on the this github and downloaded everything, until i came to the auth.json file where file path was missing, so i added it like it was stated in the video and it still didn't work.
![Cafgpture](https://github.com/sim0n00ps/OF-DL/assets/143967084/86eed8df-62f0-4894-bd49-0678b7c398e0)
![Cdfdfapture](https://github.com/sim0n00ps/OF-DL/assets/143967084/9704f216-56b0-4428-a723-2694feff7d0e)

**Comment by melithine** [comment]
The easiest solution is just to put it in the same directory as OF-DL.exe and you don't have to worry about it. Outside of that, the path looks very strange, user profiles are not usually stored inside a Program Files directory. I suspect the path is not correct as it stands.

**Comment by Cagecellag** [comment]
> The easiest solution is just to put it in the same directory as OF-DL.exe and you don't have to worry about it. Outside of that, the path looks very strange, user profiles are not usually stored inside a Program Files directory. I suspect the path is not correct as it stands.

the path is correct, i made it scuffed on purposes. Thanks for the help.

**Comment by whimsical-c4lic0** [comment]
OF-DL will attempt to auto-detect the FFmpeg path, so if you put `ffmpeg.exe` in the same directory as `OF-DL.exe` the config value is optional. Be sure to omit it from the config if you do so though. Any value in the config will override the auto-detection.

If you are going to manually configure the FFmpeg path location, add that value to `config.json` instead of `auth.json`. The FFmpeg config was officially moved to `config.json`. `auth.json` is still supported to avoid breaking people's configs, but the capitalization is important. `FFmpegPath` if defined in `config.json` and `FFMPEG_PATH` if defined in `auth.json`
