### ISSUE TITLE
Not sure what I am missing or not doing right

### ISSUE THREAD

**Issue by Daironman78** [sim0n00ps/OF-DL#451]
![Screenshot (2)](https://github.com/sim0n00ps/OF-DL/assets/81696044/e10b17cb-57a3-4a5d-b314-cecf22da967e)

I attempted to download the latest version and entered all of my info on the JSON correctly but it is giving me the attached message. Can someone please let me know what I need to do. Thanks

**Comment by Daironman78** [comment]
And this is how my Json is showing: 

{
  "USER_ID": "xxxxxxx",
  "USER_AGENT": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0",
  "X_BC": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "COOKIE": "auth_id=xxxxxxxx; sess=xxxxxxxxxxxxxxxxx;"
}

**Comment by VictorAm123** [comment]
I have the exact same issue.

**Comment by diestor** [comment]
I haven't tested it, but I assume your problem can be fixed by pasting the whole text in Cookie. I mean, it should look like this: __cf_bm=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; _cfuvid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; sess=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; lang=en; auth_id=xxxxxxxxx; cookiesAccepted=all; st=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; ref_src=
Please, let us knows if this fixes the issue.
This was in the video.

**Comment by Daironman78** [comment]
Nevermind. I figured out what it was. So if you look at that instruction video that is tied to the latest version, at the 1:40 minute mark where you add the path to the Config Json, you have to change the direction of the \ to / when adding the path. Example C:\Folder\New Version\File.exe , needs to change to C:/Folder/NewVersion/then make sure you add ffmpeg.exe at the end. Thats what I was missing. I did that and it opened right up.  Thanks guys and thanks Sim0n00ps for this build.
