### ISSUE TITLE
OF-DL Not Finding All Free Posts

### ISSUE THREAD

**Issue by ViRGEdx** [sim0n00ps/OF-DL#8]
Hi,

OF-DL seems to be struggling with an account I follow with a fairly large number of media files. While the account offers ~2600 pieces of media, OF-DL is only finding 2261 files.

Curiously, the breaking point is the end of 2022. It's finding (seemingly) everything posted in 2020, 2021, and 2022, but not anything that was posted in 2023.

The program otherwise seems to be behaving correctly - and didn't have issues downloading newer files from other accounts - so I'm at a bit of a loss as to what's going wrong.

**Comment by sim0n00ps** [comment]
I am aware of this, I have 2 accounts this has happened to so I will look into what is going on and see if I can get a fix together.

**Comment by sim0n00ps** [comment]
When I first discovered the issue I let the account fully download, I just ran it again on that account on the latest release and it downloaded all of the missing stuff so I'm not sure what the cause could be.

**Comment by ViRGEdx** [comment]
Re-running it is not finding any of the newer posts. OF-DL still thinks it has everything.

Given the post walking works chronologically backwards, it's all a bit odd. But without more of an idea of what OF-DL is doing at any given time (e.g. verbosity), I can't hazard a guess as to what's going on to miss those posts.

**Comment by sim0n00ps** [comment]
Latest version is now getting all of the posts on the 2 accounts it was happening to before. Try the latest version if you haven't already, its 1.6.1 and see if it makes any difference.

**Comment by ViRGEdx** [comment]
Yeah, this is on 1.6.1. It's not seeing the missing posts.

**Comment by sim0n00ps** [comment]
> Yeah, this is on 1.6.1. It's not seeing the missing posts.
> 
> Edit: And while this doesn't warrant a new post, I'm also seeing that OF-DL is failing to pick up some new posts from another account that were made a couple of hours ago
> 
> Edit 2: And just to talk to myself a bit more, is it possible there's there a bug with the date code, which is leading to all of thise? Those new videos that were uploaded today that I mentioned did in fact download, but OF-DL is dating them as 3 days earlier than they actually are

Just seen your edits now. 

First of all just to clarify the video might be dated 3 days earlier than the post it is included in because the user may have uploaded that media to OF but they made a post with that media 3 days later hence why it has the difference. Also the post might have been scheduled to be posted in 3 days time from when the media is uploaded. So therefore the date that is being written to the files metadata is the date that media was uploaded to OF. 

This is a strange bug I have encountered myself and it has been hit and miss. I have seen it on some accounts and I've let it download what it finds, then I've run it again a few days later and the rest is picked up. Hard to tell exactly what is making this occur. 

If you could confirm is this happening with a creator with a fair sum of posts and media or someone who doesn't have a lot? That would definitely help me understand what's going on and what the potential causes could be.

**Comment by sim0n00ps** [comment]
If you want to try the latest release 1.7 and see if it has any difference, it probably wont but worth a shot. Make sure to grab the latest changes to the auth.json file as some more fields have been added and make sure to include the .dll file included in the zip in the same folder as where you intend to run OF DL.exe from

**Comment by ViRGEdx** [comment]
It's hard to tell if everything is working quite as it should. It looks like filename-based dupe checking is broken, as OF-DL 1.7 is trying to download everything again, rather than recognizing that it already has a bunch of files that were previous downloaded.

**Comment by sim0n00ps** [comment]
> Unfortunately, it's hard to tell if everything is working quite as it should. It looks like filename-based dupe checking is broken, as OF-DL 1.7 is trying to download everything again, rather than recognizing that it already has a bunch of files that were previously downloaded by 1.6.1.

I'm already aware of this, should be a small fix. Will create a new release soon.

**Comment by mediaburnwayne** [comment]
So the did the latest include the API call changes? I am still encountering accounts where free and some paid are not pulling videos. Thanks for your work on this.
